baseURL = 'https://ankel.github.io/'
languageCode = "en-us"
title = "Ankel's homepage"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true
